### ISSUE TITLE
Incorrect generation when enum has only one value

### ISSUE THREAD

**Issue by Meterius** [johngeorgewright/runtyping#205]
```
export enum E {
  S
}

export type F = string | E;
```
generates something like
```
export const E = Literal(import("...").E);

export const F = String.Or(Literal(_S.S));
```

This appears to be caused by ts-morph giving back as the type for a enum declaration with only one value the enum member type itself. Thus in ```factory``` the ```isLiteral``` case is triggered instead of ```isEnum``` and in ```enumMemberTypeGenerator``` the ```enumType``` will equal ```enumMemberType```. 

The ```name``` for ```enumTypeGenerator``` could be determined via ```(type.isEnumLiteral() ? type.getSymbolOrThrow().getDeclarations()[0].getParentOrThrow() : type).getSymbolOrThrow().getName()``` (assuming the case in factory is adjusted). And ```enumTypeName``` in ```enumMemberTypeGenerator``` could be determined via ```enumMemberType.getSymbol()?.getDeclarations()[0].getParent()?.getSymbol()?.getName()```.

**Comment by johngeorgewright** [comment]
Sorry for the lack of response on this, but you're right, this is a problem with ts-morph. We may need to bring it up with them.
