### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sstur** [johngeorgewright/runtyping#314]
It seems Runtyping doesn't handle circular references, which might be a known limitation, but I wanted to bring this up in case it's something you'd be willing to support (or accept a PR for).

One-click repro: [https://stackblitz.com/edit/node-gs3ck3?file=src/main.ts](https://stackblitz.com/edit/node-gs3ck3?file=src/main.ts)

When trying to convert the following TS types to Runtypes we get an error saying "Maximum call stack size exceeded".

```ts
type Student = {
  type: 'student';
  teacher: Teacher;
};

type Teacher = {
  type: 'teacher';
  students: Array<Student>;
};

export type User = Student | Teacher;
```

I know recursive types like this is an advanced use case and it's not trivial to write manually, but I figure that's all the more reason for a tool like this to handle the complexity for us!

Turns out to correctly write such Runtypes by hand, we need to use `Lazy()` as described [here](https://github.com/pelotom/runtypes/issues/14).

With this approach we'd end up with something like:

```ts
import { Array, Lazy, Literal, Record, Runtype } from 'runtypes';

type Student = {
  type: 'student';
  teacher: Teacher;
};

type Teacher = {
  type: 'teacher';
  students: Student[];
};

// Here we use Lazy() since we need to reference Teacher before it's defined. We
// also need to give TS a type hint since it can't infer the type when using
// Lazy like this.
export const Student: Runtype<Student> = Lazy(() =>
  Record({
    type: Literal('student'),
    teacher: Teacher,
  }),
);

export const Teacher = Record({
  type: Literal('teacher'),
  students: Array(Student),
});

export const User = Student.Or(Teacher);
```

Is this within scope for this project? Should I try to make a PR to address this?

**Comment by johngeorgewright** [comment]
Thanks for the heads up. And yes, looks like something that could be added to this project. We already use `Lazy` if there's a recursive reference. This is quite different, however, and will be an interesting problem to solve.

**Comment by sstur** [comment]
Thanks for taking a look at this issue!

I had a poke around in `src/Generator.ts` and I noticed the function `isRecursive()` seems like you're already handling the base case of recursive types, those that reference themselves directly, e.g. `type Foo = string | Array<Foo>`. But this indirect kind (A references B which references A) is non-trivial since it's like walking a graph looking for a loop. I imagine there's utilities for this sort of thing, but I haven't gotten that far down the path of finding a solution. Will let you know if I can find something.

Thanks!

**Comment by sstur** [comment]
Wow, this is incredible, thanks so much!

**Comment by sstur** [comment]
Oh hey, the latest release seems to have a missing import in [dist/index.js](https://unpkg.com/browse/runtyping@4.6.0/dist/index.js) on line 5. It's referring to `require("./Generator")` but there is no such file, as you can see [here](https://unpkg.com/browse/runtyping@4.6.0/dist/). Sorry if this should be a new issue.

**Comment by r3wt** [comment]
@johngeorgewright i take it this isn't fixed for `runtypes` yet? I am facing the same issue. trying to extract the types from Mongoose models, so i can use them to validate request body at runtime
