### ISSUE TITLE
Incorrect path when importing original types

### ISSUE THREAD

**Issue by sstur** [johngeorgewright/runtyping#334]
If I have the following source types:

<details>
  <summary><code>src/types/Foo.ts</code></summary>

```ts
export type Foo = { type: 'foo'; children: Array<Bar> };

export type Bar = { type: 'bar'; parent: Foo };
```

</details>

...and I generate runtypes using the following script:

<details>
  <summary><code>src/cli/generate.ts</code></summary>

```ts
import { Generator } from '@runtyping/runtypes';

const generator = new Generator({
  targetFile: 'src/generated/runtypes.ts',
  // optional: runtypeFormat / typeFormat (see above)
});

generator
  .generate([
    { file: 'src/types/Foo.ts', type: 'Foo' },
    // { file: 'json/my-json-schema.json', type: 'ExampleType' },
  ])
  .then((file) => file.save());
```

</details>

... then I'll get the following output. Note the path is wrong (and it has a .ts at the end).

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/369384/180082563-5eff2ff8-cd9d-4454-9aa5-e79edda60a9a.png">

**Comment by johngeorgewright** [comment]
This is one of those times where saying, "it's a feature, not a bug", is actually true.

The feature here is that the source file *could* be from a dependency module. Using the syntax `src/types/Foo.ts` is like saying `node_modules/src/types/Foo.ts`. Instead, use `./src/types/Foo.ts` or resolve the absolute path.

**Comment by sstur** [comment]
OMG, you're right! I changed `{ file: 'src/types/Foo.ts' }` to `{ file: './src/types/Foo.ts' }` in my `generate.ts` above and it correctly computed the relative path. I now see this following generated output, which works correctly.

<img width="1124" src="https://user-images.githubusercontent.com/369384/180242360-75ca37dc-1c56-4a5b-908b-abe9cd66d2f6.png">

Thanks so much!
