### ISSUE TITLE
Never type is not parsed

### ISSUE THREAD

**Issue by AsPulse** [johngeorgewright/runtyping#399]
As the title says, if you use the NEVER type, you will get `Error: !!! TYPE never NOT PARSED !!!` will be displayed.

You may think that you would never use never in a type definition, but it appears in the form `Record<string, never>`(in runtypes: `Dictionary(String, Never)`) when you want to define an "Object that contains nothing".

I'd like to see support for parse of type never! (Or is there another way to represent an empty object...?)

(thanks for making runtyping! I'm commenting from Japan, so apologies if my English is wrong)

**Comment by johngeorgewright** [comment]
That's a good point. I never wrote any tests that handle a `never` type. I'll think about how that can be handled.

> Or is there another way to represent an empty object...?

I'm fairly sure that you can use `{}` instead of `Record<string, never>`. So that might help you until I fix this.

**Comment by AsPulse** [comment]
I'm not familiar with runtypes and this is just pure TypeScript...

```ts
type EmptyObject = {};

const a: EmptyObject = {} //No Error
const b: EmptyObject = { hoge: "aaa" } //No Error
const c: EmptyObject = "hoge" //No Error
```

In a pure TypeScript type system, `{}` fits all types except null and undefined.

If it is treated as an "empty object" on runtypes when I use `{}`, which may achieve my goal.
But that is different from the TypeScript type system...
(I don't know if this is the desired behavior or not)

But for the reasons above, there are tools that warn you to use `Object`, `unknown` or `Record<string, never>` instead for the type `{}`.

**Comment by AsPulse** [comment]
(Nevertheless, thanks for the fix!)
